### ISSUE TITLE
Adding a few channels to bench

### ISSUE THREAD

**Issue by v1gnesh** [kprotty/uchan#3]
I did see the note in the README about where to add them, however, I don't know enough about macros to add in these implementations where the imports look different.

If you have time or interest, could you consider adding these please:

https://docs.rs/tokio/latest/tokio/sync/oneshot/index.html
```rust
use tokio::sync::oneshot;

#[tokio::main]
async fn main() {
    let (tx, rx) = oneshot::channel();
```

https://docs.rs/tokio/latest/tokio/sync/mpsc/fn.channel.html
```rust
use tokio::sync::mpsc;

#[tokio::main]
async fn main() {
    let (tx, mut rx) = mpsc::channel(100);
```

https://docs.rs/futures-channel/latest/futures_channel/oneshot/fn.channel.html
```rust
use futures::channel::oneshot;
use std::{thread, time::Duration};

let (sender, receiver) = oneshot::channel::<i32>();
```

Ones without examples:
https://docs.rs/tokio/latest/tokio/sync/mpsc/fn.unbounded_channel.html
https://docs.rs/futures-channel/latest/futures_channel/mpsc/fn.channel.html
https://docs.rs/futures-channel/latest/futures_channel/mpsc/fn.unbounded.html

Also a few questions:
Is there such a thing as spmc?
What optimizations are possible for this use case... things that spmc in particular can take advantage of.

**Comment by kprotty** [comment]
`uchan` is a drop-in for std's mpsc which is synchronous so it's not too fair to compare it to asynchronous channels which have more complicated blocking routines.

But for your questions, yes there is an spmc; [`crossbeam-deque`](https://docs.rs/crossbeam-deque/latest/crossbeam_deque/) is a good example. A `Worker` is not `Sync` and can send/recv. It can also create `Stealer`s which are Sync but can only `recv`. The advantage is that send doesn't have to synchronize with others (i.e. use read-modify-write/RMW atomics) so it can stick to only atomic loads/stores for the most part.

**Comment by v1gnesh** [comment]
> `uchan` is a drop-in for std's mpsc which is synchronous so it's not too fair to compare it to asynchronous channels which have more complicated blocking routines.

Time for a dumb question... is **tokio::sync::**{oneshot, mpsc} not synchronous?

**Comment by kprotty** [comment]
Their send is synchronous, but their recv is asynchronous which is what matters.

**Comment by v1gnesh** [comment]
Cool, thanks for clarifying :+1:
